language: perl
perl:
  - "5.24"
addons:
  postgresql: 9.5
env:
  global:
    - HARNESS_OPTIONS=j9
    - TEST_ONLINE=postgresql://postgres@/test_pg
install:
  - cpanm -n --installdeps .
before_script:
  - psql -U postgres -c 'create database test_pg'
sudo: false
notifications:
  email: true
