language: perl
perl:
  - "5.24"
addons:
  postgresql: 9.4
env:
  global:
    - HARNESS_OPTIONS=j9
    - TEST_ONLINE=postgresql://postgres@/test_pg
install:
  - cpanm -n --installdeps .
before_script:
  - psql -U postgres -c 'create database test_pg'
script:
  - prove -rl
after_failure: "cat ~/.cpanm/build.log"
sudo: false
notifications:
  email: false
